# Generated by Django 4.1.6 on 2023-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='category',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], default=1, max_length=100),
        ),
    ]
