# Generated by Django 4.1.6 on 2023-03-06 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0002_alter_statement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
