# Generated by Django 4.1.6 on 2023-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=6)),
                ('pronouns', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('department', models.CharField(choices=[('Accounting & Finance', 'Accounting & Finance'), ('Advertising & Marketing', 'Advertising & Marketing'), ('Graphic Design', 'Graphic Design'), ('Human Resources', 'Human Resources'), ('IT', 'IT')], default='Accounting & Finance', max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
