# Generated by Django 4.1.6 on 2023-03-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
